/* `outils/gabarit/_admin1.html` — la fenêtre « Réglages du plan » et ses
   onglets, la fiche d'une zone organisateur, le placement des libellés. */
module.exports = {
  // les commandes du plan
  "Afficher les icônes de zoom": "Show the zoom buttons",
  "Afficher l'échelle": "Show the scale",
  "Proposer le parcours de visite": "Offer the visit plan",
  "Proposer le calcul d'itinéraire": "Offer directions",

  // l'onglet « Recherche »
  "Stands et exposants": "Stands and exhibitors",
  "Le nom d'une enseigne, son numéro d'emplacement, son secteur, ses thématiques, et les sociétés hébergées sur un stand partagé.":
    "A brand's name, its stand number, its sector, its themes, and the companies hosted on a shared stand.",
  "Ce salon ne porte aucun emplacement.": "This show has no stands.",
  "Accueil, restauration, village start-up — les endroits que le salon fournit avec son plan.":
    "Reception, catering, start-up village — the places the show provides along with its map.",
  "Ce salon ne porte aucune zone organisateur.": "This show has no organiser areas.",
  "Le titre d'une session, sa salle, son thème, et l'exposant qui la tient — souvent le seul nom dont on se souvienne.":
    "A session's title, its room, its theme, and the exhibitor running it — often the only name people remember.",
  "Le programme n'est pas synchronisé : sa source se règle depuis la console, dans « Source des données ».":
    "The programme is not synchronised: its source is set in the console, under “Data sources”.",
  "Produits": "Products",
  "Ce que les exposants présentent, nommé produit par produit.": "What exhibitors present, named product by product.",
  "Les produits ne sont pas encore repris par la synchronisation, quelle que soit la source réglée dans la console.":
    "Products are not yet picked up by the synchronisation, whatever source is set in the console.",
  "Les repères posés sur le plan : entrées, WC, escaliers, parkings, vestiaires. Le cartouche du bas les récapitule de son côté, que cette case soit cochée ou non.":
    "The landmarks placed on the map: entrances, toilets, stairs, car parks, cloakrooms. The panel at the bottom lists them anyway, whether this box is ticked or not.",
  "Aucun repère n'est posé sur les plans de ce salon : ils se dessinent depuis la boîte à outils.":
    "No landmarks are placed on this show's maps: they are drawn from the toolbox.",
  "Ce que le champ de recherche remonte. Le sommaire du pavillon n'en dépend pas : sans mot-clé, la liste reste celle de ses emplacements. Publiez la configuration pour que le changement parvienne aux visiteurs.":
    "What the search box brings up. The hall's list does not depend on it: without a keyword, the list stays that of its stands. Publish the configuration for the change to reach visitors.",

  // les modèles d'habillage
  "Sobre": "Plain",
  "Le rendu d'origine : un seul rythme, de la liste à la fiche.": "The original look: one rhythm, from the list to the details.",
  "Grille": "Grid",
  "Encre pleine, numéro en filigrane, filets francs jusque dans la liste.": "Solid ink, watermarked number, crisp rules right down the list.",
  "Console": "Console",
  "Chasse fixe et invites de commande, sur un phosphore à la couleur du salon.": "Monospace type and command prompts, on a phosphor glow in the show's colour.",
  "Billet": "Ticket",
  "Bandeau d'accent sur la recherche, numéros comptables, lignes perforées.": "Accent band on the search, ledger numbers, perforated lines.",
  "Magazine": "Magazine",
  "Serif à fort contraste et italiques : le catalogue et son sommaire.": "High-contrast serif and italics: the catalogue and its contents page.",
  "Brut": "Raw",
  "Trait épais, ombre dure, aplat franc. Papier et noir dans les deux thèmes.": "Thick lines, hard shadows, flat colour. Paper and black in both themes.",
  "Verre": "Glass",
  "Un bloc de la couleur du salon, champs et lignes en carreaux translucides.": "A block in the show's colour, with fields and rows as translucent panes.",
  "Kraft": "Kraft",
  "Carton et machine à écrire, « nouvel exposant » tamponné de travers.": "Cardboard and typewriter, with “new exhibitor” stamped askew.",
  "Signalétique": "Signage",
  "Aplat, flèche et capitales : un stand se lit comme une direction de hall.": "Flat colour, arrows and capitals: a stand reads like a hall sign.",
  "Chronologie": "Timeline",
  "Le programme en ligne de temps, et la liste égrenée le long du même rail.": "The programme as a timeline, and the list strung along the same rail.",
  "Nu": "Bare",
  "Ni cadre ni libellés : la hiérarchie typographique seule.": "No frames, no labels: typographic hierarchy alone.",

  // l'aperçu des modèles, sur une fiche d'exemple — les noms propres et
  // l'adresse d'un exposant imaginaire restent ce qu'ils sont
  "Ateliers Ligneron": "Ateliers Ligneron",
  "Ligneron & Fils SARL": "Ligneron & Fils SARL",
  "8 rue de la Filature": "8 rue de la Filature",
  "Nantes": "Nantes",
  "France": "France",
  "Atelier du Marais": "Atelier du Marais",
  "Bois & Compagnie": "Bois & Compagnie",
  "Duchêne Agencement": "Duchêne Agencement",
  "Fonderie de l'Ouest": "Fonderie de l'Ouest",
  "Granit Armor": "Granit Armor",
  "Habitat Lumière": "Habitat Lumière",
  "Menuiseries Rocher": "Menuiseries Rocher",
  "Pavillon 2": "Hall 2",
  "Aménagement & second œuvre": "Fit-out & finishing works",
  "Menuiserie;Agencement de boutique": "Joinery;Shop fitting",
  "Réemploi;Bois de pays": "Reuse;Local timber",
  "Menuiserie": "Joinery",
  "Agencement de boutique": "Shop fitting",
  "Réemploi": "Reuse",
  "Bois de pays": "Local timber",
  "Valeur d'exemple": "Sample value",
  "Le bois de pays dans la commande publique": "Local timber in public procurement",
  "Table ronde": "Round table",
  "Agencer une boutique en réemploi": "Fitting out a shop with reused materials",
  "Démonstration": "Demonstration",

  // la fenêtre et ses onglets
  "Plan": "Map",
  "Recherche": "Search",
  "Fiche Stand": "Stand details",
  "Apparence": "Appearance",
  "Zones": "Areas",
  "PMR": "Accessibility",

  // l'onglet « Zones »
  "Ce que le visiteur lit sur une zone organisateur. La source n'en donne que le contour et parfois un nom : le reste s'écrit ici, et paraît sans attendre la prochaine synchronisation.":
    "What visitors read about an organiser area. The source only gives its outline and sometimes a name: the rest is written here, and shows up without waiting for the next synchronisation.",
  "fiche": "details",
  "traversée": "walk-through",
  "masquée": "hidden",
  "Logo": "Logo",
  "L'image déposée sur la zone, dans l'en-tête de sa fiche.": "The image uploaded for the area, at the top of its details.",
  "Ce qu'on trouve dans la zone, ses horaires, ses conditions d'accès. Elle ne paraît que sur les zones où elle est remplie.":
    "What you find in the area, its opening hours, how to get in. It only appears on areas where it has been filled in.",
  "La page où en savoir plus, saisie avec la description.": "The page to find out more, entered with the description.",
  "Le programme tenu dans la zone, par ordre chronologique.": "The programme held in the area, in chronological order.",
  "Ce que la fiche montre": "What the details show",
  "Les champs qu'une fiche de zone déroule, pour toutes les zones à la fois. Un champ décoché reste écrit : il cesse de paraître, et revient tel quel en le recochant.":
    "The fields an area's details show, for all areas at once. An unticked field stays written: it stops appearing, and comes back as it was when ticked again.",
  "Ces cases s'enregistrent dès qu'on les coche.": "These boxes are saved as soon as they are ticked.",
  "Enregistré.": "Saved.",
  "Échec : {raison}": "Failed: {raison}",
  "retirée du plan public": "removed from the public map",
  "Ce que vous écrivez est enregistré en quittant la fiche.": "What you write is saved when you leave these details.",

  // l'onglet « Plan »
  "Ce que les visiteurs voient sur le plan. Publiez la configuration pour que le changement leur parvienne.":
    "What visitors see on the map. Publish the configuration for the change to reach them.",
  "Montrer les secteurs — couleurs et filtre": "Show sectors — colours and filter",
  "Suivre les allées une à une — pour un hall arrondi ou aux rangées désaccordées":
    "Follow the aisles one by one — for a rounded hall or one with uneven rows",
  "Compter les co-exposants sur le plan": "Count co-exhibitors on the map",
  "Afficher la liste des co-exposants au clic sur le stand": "Show the list of co-exhibitors when the stand is clicked",
  "min": "min",
  "Temps de visite par stand": "Visiting time per stand",
  "Sert à organiser la journée d'un visiteur depuis son parcours : c'est ce qui décide combien de stands tiennent entre deux conférences.":
    "Used to plan a visitor's day from their visit plan: it decides how many stands fit between two conferences.",
  "Dates et heures d'ouverture du salon": "Show dates and opening hours",
  "Du": "From",
  "au": "to",
  "Premier jour du salon": "First day of the show",
  "Dernier jour du salon": "Last day of the show",
  "Le dernier jour précède le premier : corrigez les dates pour régler les heures.":
    "The last day comes before the first: correct the dates to set the hours.",
  "Plus de {n} jours entre ces deux dates : seuls les {n2} premiers sont proposés. Vérifiez l'année.":
    "More than {n} days between these two dates: only the first {n2} are offered. Check the year.",
  "Une fermeture tombe avant l'ouverture : ce jour-là n'a pas d'heures tant qu'elle n'est pas corrigée.":
    "A closing time comes before the opening time: that day has no hours until it is corrected.",
  "Ouverture": "Opening",
  "Fermeture": "Closing",
  "Effacer les heures de ce jour": "Clear this day's hours",
  "Ouverture, {jour}": "Opening, {jour}",
  "Fermeture, {jour}": "Closing, {jour}",
  "Aucun stand n'est programmé dans la journée d'un visiteur avant l'ouverture ni après la fermeture. Ces jours sont aussi ceux qu'on lui propose. Un jour sans heures n'a pas de borne.":
    "No stand is scheduled in a visitor's day before opening or after closing. These days are also the ones offered to visitors. A day without hours has no limits.",
  "Choisissez les dates : une ligne d'heures paraît pour chaque jour. Sans elles, la journée d'un visiteur n'a ni début ni fin.":
    "Choose the dates: a row of hours appears for each day. Without them, a visitor's day has no start and no end.",

  // l'onglet « PMR »
  "L'itinéraire accessible contourne déjà ce qui est dessiné infranchissable. Ceci vise ce qu'aucun dessin ne porte : la foule d'une entrée ou d'une sortie de conférence, aux abords de la salle. Le trajet du marcheur, lui, n'en tient pas compte — il s'y faufile.":
    "The accessible route already avoids whatever is drawn as impassable. This targets what no drawing shows: the crowd going into or out of a conference, around the room. The walking route ignores it — people on foot squeeze through.",
  "Écarter l'itinéraire accessible des salles qui se vident": "Keep the accessible route away from rooms that are emptying",
  "Un mètre longé en vaut": "One metre alongside counts as",
  "mètres": "metres",
  "Trois : le trajet accepte un détour jusqu'au double de ce qu'il aurait longé, et passe tout de même s'il n'existe pas d'autre chemin. À un, plus rien ne l'écarte.":
    "Three: the route accepts a detour of up to twice what it would have gone alongside, and still goes through if there is no other way. At one, nothing keeps it away any more.",
  "Largeur des abords": "Width of the surroundings",
  "Depuis le contour de la salle, et seulement là : c'est la portion qui la jouxte qui coûte cher, pas l'allée d'un bout à l'autre. Quatre mètres valent une allée courante.":
    "From the outline of the room, and only there: it is the stretch right next to it that costs, not the whole aisle. Four metres is a standard aisle.",
  "Autour de l'heure dite": "Around the scheduled time",
  "Avant et après le début, avant et après la fin de chaque conférence. En dehors de ces minutes, le trajet est celui de toujours.":
    "Before and after the start, before and after the end of each conference. Outside these minutes, the route is the usual one.",

  // l'onglet « Apparence »
  "Bleu d'encre": "Ink blue",
  "Bleu roi": "Royal blue",
  "Bleu nuit": "Midnight blue",
  "Bleu canard": "Teal blue",
  "Turquoise": "Turquoise",
  "Vert prairie": "Meadow green",
  "Vert forêt": "Forest green",
  "Olive": "Olive",
  "Or brûlé": "Burnt gold",
  "Ambre": "Amber",
  "Terracotta": "Terracotta",
  "Brique": "Brick",
  "Grenat": "Garnet",
  "Cerise": "Cherry",
  "Framboise": "Raspberry",
  "Fuchsia": "Fuchsia",
  "Violet": "Violet",
  "Indigo": "Indigo",
  "Prune": "Plum",
  "Brun": "Brown",
  "Ardoise": "Slate",
  "Anthracite": "Charcoal",
  "La couleur principale sert partout : sélection, liens, boutons, pastilles, et les modèles s'en habillent. Le modèle décide de l'allure de tout l'écran à la fois : le bandeau du haut, la liste des exposants, la fiche qui s'ouvre sur un stand, le parcours de visite et l'itinéraire. Il pose aussi sa police sur les noms des stands et des zones : une autre peut lui être préférée, jusqu'au prochain changement de modèle. Les numéros de stand gardent la sienne.":
    "The main colour is used everywhere: selection, links, buttons, badges, and the templates dress themselves in it. The template sets the look of the whole screen at once: the top bar, the exhibitor list, the details that open on a stand, the visit plan and the directions. It also sets the font of stand and area names: another one can be preferred, until the template changes again. Stand numbers keep their own.",
  "Couleur principale": "Main colour",
  "Réglage d'origine": "Original setting",
  "Modèle d'habillage": "Template",

  // la police des noms
  "Police des noms": "Name font",
  "Police du modèle": "Template font",
  "du modèle": "from the template",
  "modèle {modele}": "{modele} template",
  // les genres, qui filtrent les vignettes
  "Sans serif": "Sans serif",
  "Étroites": "Condensed",
  "Serif": "Serif",
  "Arrondies": "Rounded",
  "Haute lisibilité": "High legibility",
  "Affiche": "Display",
  "Manuscrites": "Handwritten",
  "Chasse fixe": "Monospace",
  // les noms des polices, identiques dans les deux langues
  "Archivo": "Archivo",
  "Barlow": "Barlow",
  "DM Sans": "DM Sans",
  "Fira Sans": "Fira Sans",
  "IBM Plex Sans": "IBM Plex Sans",
  "Instrument Sans": "Instrument Sans",
  "Inter": "Inter",
  "Jost": "Jost",
  "Lato": "Lato",
  "Manrope": "Manrope",
  "Montserrat": "Montserrat",
  "Noto Sans": "Noto Sans",
  "Open Sans": "Open Sans",
  "Plus Jakarta Sans": "Plus Jakarta Sans",
  "Poppins": "Poppins",
  "Raleway": "Raleway",
  "Roboto": "Roboto",
  "Source Sans 3": "Source Sans 3",
  "Space Grotesk": "Space Grotesk",
  "Work Sans": "Work Sans",
  "Anton": "Anton",
  "Archivo Narrow": "Archivo Narrow",
  "Barlow Condensed": "Barlow Condensed",
  "Bebas Neue": "Bebas Neue",
  "Fira Sans Condensed": "Fira Sans Condensed",
  "Oswald": "Oswald",
  "PT Sans Narrow": "PT Sans Narrow",
  "Roboto Condensed": "Roboto Condensed",
  "Bitter": "Bitter",
  "Cormorant Garamond": "Cormorant Garamond",
  "EB Garamond": "EB Garamond",
  "Fraunces": "Fraunces",
  "Libre Baskerville": "Libre Baskerville",
  "Lora": "Lora",
  "Merriweather": "Merriweather",
  "Playfair Display": "Playfair Display",
  "PT Serif": "PT Serif",
  "Roboto Slab": "Roboto Slab",
  "Source Serif 4": "Source Serif 4",
  "Comfortaa": "Comfortaa",
  "Fredoka": "Fredoka",
  "Nunito": "Nunito",
  "Quicksand": "Quicksand",
  "Varela Round": "Varela Round",
  "Andika": "Andika",
  "Atkinson Hyperlegible Next": "Atkinson Hyperlegible Next",
  "Lexend": "Lexend",
  "Abril Fatface": "Abril Fatface",
  "Alfa Slab One": "Alfa Slab One",
  "Archivo Black": "Archivo Black",
  "Bungee": "Bungee",
  "Righteous": "Righteous",
  "Caveat": "Caveat",
  "Dancing Script": "Dancing Script",
  "Kalam": "Kalam",
  "Patrick Hand": "Patrick Hand",
  "Courier Prime": "Courier Prime",
  "IBM Plex Mono": "IBM Plex Mono",
  "Inconsolata": "Inconsolata",
  "JetBrains Mono": "JetBrains Mono",
  "Roboto Mono": "Roboto Mono",
  "Space Mono": "Space Mono",
  // l'onglet « Fiche Stand »
  "L'ordre dans lequel la fiche déroule ses champs, de haut en bas : ce que le visiteur vient lire en premier n'est pas le même d'un salon à l'autre. Attrapez une ligne par sa poignée, ou servez-vous des flèches. L'en-tête — l'enseigne, le pavillon, le numéro de stand — et le volet des conférences n'en font pas partie : ils ne se déplacent pas.":
    "The order in which the details list their fields, from top to bottom: what visitors come to read first differs from one show to the next. Grab a row by its handle, or use the arrows. The header — the brand, the hall, the stand number — and the conferences panel are not part of it: they don't move.",
  "Aperçu": "Preview",
  "La fiche telle que le visiteur la recevra : l'habillage retenu pour ce salon, et les valeurs du stand qui remplit le mieux les champs affichés. Sur téléphone, les champs qui tiennent en un mot se rangent deux par deux.":
    "The details as visitors will get them: the template chosen for this show, and the values of the stand that best fills the fields shown. On phones, fields that fit in one word are laid out two by two.",
  "Regrouper": "Group",
  "Monter": "Move up",
  "Descendre": "Move down",
  "Monter {champ}": "Move up {champ}",
  "Descendre {champ}": "Move down {champ}",
  "Réunir {champ}": "Group {champ}",
  "propre au salon": "specific to this show",
  "Masqué : ce champ ne paraît pas sur la fiche.": "Hidden: this field does not appear in the details.",
  "Sortir « {champ} » du groupe": "Take “{champ}” out of the group",
  "Titre du groupe": "Group title",
  "Défaire le groupe": "Ungroup",
  "Cochez au moins deux champs pour les réunir sous un même titre.": "Tick at least two fields to group them under one title.",
  "Réunir {n} champs sous un même titre.": "Group {n} fields under one title.",

  // la barre d'administration
  "Télécharger une sauvegarde": "Download a backup",
  "Restaurer une sauvegarde…": "Restore a backup…",

  // la fiche d'une zone
  "Libellé": "Label",
  "Le nom de la zone, sur le plan comme sur sa fiche. Laissez vide pour revenir au nom d'origine, s'il y en a un.":
    "The area's name, on the map and in its details. Leave empty to go back to the original name, if there is one.",
  "Agora, Halte-garderie, Pitch Retail…": "Agora, Crèche, Pitch Retail…",
  "Libellé en français": "Label in French",
  "Libellé en anglais": "Label in English",
  "Le nom de la zone dans la version anglaise du plan. Laissé vide, c'est le libellé en français qui s'y affiche.":
    "The area's name in the English version of the map. Left empty, the French label is shown there.",
  "Agora, Childcare, Pitch Retail…": "Agora, Childcare, Pitch Retail…",
  "Description en français": "Description in French",
  "Description en anglais": "Description in English",
  "Ce que lit le visiteur de la version anglaise. Laissée vide, la fiche anglaise montre la description en français.":
    "What visitors read in the English version. Left empty, the English details show the French description.",
  "Type": "Type",
  "Ouvre l'entrée correspondante dans le cartouche des points d'intérêt, au bas du plan : le visiteur y retrouve d'un geste toutes les zones du même type. Sans type, la zone reste sur le plan comme aujourd'hui.":
    "Opens the matching entry in the points of interest panel, at the bottom of the map: visitors find all areas of the same type there in one tap. Without a type, the area stays on the map as it is today.",
  "L'itinéraire peut la traverser": "Routes can go through it",
  "Les trajets coupent par cette zone au lieu d'en faire le tour. À cocher sur un accueil, une agora, une esplanade — tout sol qu'on franchit à pied. À laisser décoché sur une réserve, un local technique, un espace clos : le trajet les contourne, comme un stand.":
    "Routes cut through this area instead of going around it. Tick it for a reception, an agora, a forecourt — any floor people walk across. Leave it unticked for a storeroom, a service room, an enclosed space: the route goes around them, like a stand.",
  "Ce qu'on trouve dans cette zone, ses horaires, ses conditions d'accès. Le libellé « Description » ne paraît sur la fiche que si vous en écrivez une.":
    "What you find in this area, its opening hours, how to get in. The “Description” heading only appears in the details if you write one.",
  "Une page où en savoir plus. Elle s'ouvre dans un nouvel onglet, et n'apparaît sur la fiche que si vous en donnez une.":
    "A page to find out more. It opens in a new tab, and only appears in the details if you give one.",
  "trouvée automatiquement": "found automatically",
  "choisie à la main": "chosen by hand",
  "rattachée à {zone}": "linked to {zone}",
  "à situer": "to be located",
  "Salles de conférence": "Conference rooms",
  "Le programme du salon, salle par salle. Cochez celles qui se tiennent dans cette zone : leurs conférences paraissent aussitôt sur sa fiche. Un rattachement choisi ici n'est plus modifié par les synchronisations suivantes.":
    "The show's programme, room by room. Tick the ones located in this area: their conferences appear straight away in its details. A link chosen here is no longer changed by later synchronisations.",
  "une zone absente du plan": "an area not on the map",
  "une zone sans nom": "an unnamed area",
  "ce fichier n'est pas une image": "this file is not an image",
  "fichier illisible": "unreadable file",
  "image illisible": "unreadable image",
  "image trop lourde, même réduite — un logo, pas une photo": "image too heavy, even reduced — a logo, not a photo",
  "Retirer": "Remove",
  "Aucun logo": "No logo",
  "Remplacer…": "Replace…",
  "Choisir un fichier…": "Choose a file…",
  "Lecture…": "Reading…",
  "{n} Ko": "{n} KB",
  "L'image paraît dans l'en-tête de la fiche, au-dessus du type et du nom. Elle est réduite puis enregistrée dans la fiche : elle part avec le plan, sans dépendre d'un fichier hébergé ailleurs. Glissez-la sur la vignette, ou choisissez-la.":
    "The image appears at the top of the details, above the type and the name. It is reduced then saved in the details: it travels with the map, without depending on a file hosted elsewhere. Drag it onto the thumbnail, or choose it.",
  "Gras": "Bold",
  "Italique": "Italic",
  "Liste à puces": "Bulleted list",
  "Liste numérotée": "Numbered list",
  "Description de la zone": "Area description",
  "Ce qu'on trouve dans cette zone, ses horaires…": "What you find in this area, its opening hours…",
  "Poser": "Apply",
  "Poser un lien sur le texte choisi": "Add a link to the selected text",
  "Enregistrement de la zone impossible : {raison}": "Could not save the area: {raison}",
  "Changement impossible : {raison}": "Change failed: {raison}",

  // le placement des libellés
  "Glissez le libellé, ou ajustez-le aux flèches du clavier.": "Drag the label, or nudge it with the arrow keys.",
  "Glissez ce libellé pour le déplacer, ou tirez la taille.": "Drag this label to move it, or pull the size slider.",
};
