/* `outils/gabarit/_export.html` — le classeur des exposants, partagé par la
   console et le rapport. Ses intitulés partent traduits dans le fichier. */
module.exports = {
  "Clic sur le plan": "Click on the map",
  "Clic sur un logo ou une image": "Click on a logo or image",
  "Nom cité par une conférence": "Name mentioned by a conference",
  "Liste du pavillon": "Hall list",
  "Programme de visite": "Visit plan",
  "Proposé pour compléter une visite": "Suggested to round off a visit",
  "Lien direct": "Direct link",
  "Autre": "Other",
  "Emplacement": "Stand",
  "Exposant": "Exhibitor",
  "Fiches ouvertes": "Records opened",
  "Visiteurs uniques": "Unique visitors",
  "Itinéraires calculés": "Routes calculated",
  "Ajouts au programme de visite": "Added to a visit plan",
  "Ajouts depuis une suggestion": "Added from a suggestion",
  "Ajouts depuis un parcours reçu": "Added from a shared visit plan",
  "Total interactions": "Total interactions",
  "Visiteurs ayant demandé la route": "Visitors who asked for directions",
  "Visiteurs l'ayant mis à leur programme": "Visitors who added it to their plan",
  "Visiteurs venus d'une suggestion": "Visitors who came from a suggestion",
  "Visiteurs venus d'un parcours reçu": "Visitors who came from a shared visit plan",
  "Ouvertures": "Opens",
  "Visiteurs": "Visitors",
  "Exposants ({n} derniers jours)": "Exhibitors (last {n} days)",
  "Exposants (depuis le début)": "Exhibitors (since the start)",
  "Préparation…": "Preparing…",
  "Préparation du classeur…": "Preparing the spreadsheet…",
  "Aucun exposant à exporter : ce salon n'a pas encore été synchronisé.": "No exhibitors to export: this show has not been synchronised yet.",
  "{n} exposants exportés ({n2} derniers jours).": "{n} exhibitors exported (last {n2} days).",
  "{n} exposant exporté ({n2} derniers jours).": "{n} exhibitor exported (last {n2} days).",
  "{n} exposants exportés (depuis le début).": "{n} exhibitors exported (since the start).",
  "{n} exposant exporté (depuis le début).": "{n} exhibitor exported (since the start).",
};
