/* `outils/gabarit/_head.html` — le squelette de l'écran du plan : la barre du
   haut, la recherche, la boîte à outils de dessin, les tiroirs de la fiche, du
   parcours et de l'itinéraire. */
module.exports = {
  "Plan du salon": "Floor plan",
  "Confidentialité": "Privacy",
  "Pavillons": "Halls",
  "emplacements": "stands",
  "exposants": "exhibitors",
  "zones": "areas",

  "Calculer un itinéraire": "Get directions",
  "Mon parcours de visite": "My visit plan",
  "Calques": "Layers",
  "Réglages du plan": "Map settings",
  "Thème clair / sombre": "Light / dark theme",
  "Basculer le thème": "Switch theme",
  "Compte": "Account",
  "Thème sombre": "Dark theme",
  "Thème clair": "Light theme",
  "Se déconnecter": "Sign out",

  "Afficher la liste des stands": "Show the stand list",
  "Agrandir la fiche": "Expand the details",
  "Exposant, stand…": "Exhibitor, stand…",
  "Effacer la recherche": "Clear search",
  "Critères de recherche": "Search filters",
  "Critères retenus": "Selected filters",
  "Revenir au début": "Back to the start",
  "Voir la suite": "See more",

  "Plan du pavillon 7.1": "Map of hall 7.1",
  "Zoom avant": "Zoom in",
  "Zoom arrière": "Zoom out",
  "Ajuster": "Fit to screen",
  "Annuler": "Cancel",
  "Recommencer": "Start over",
  "© les contributeurs d'OpenStreetMap": "© OpenStreetMap contributors",

  "Renommer le calque": "Rename layer",
  "Fermer — Échap": "Close — Esc",
  "Fermer la barre de dessin": "Close the drawing toolbar",
  "Rôle dans les itinéraires": "Role in routes",
  "Voir ce qui est praticable": "Show where people can walk",
  "Accrocher aux stands et aux zones — Alt pour relâcher": "Snap to stands and areas — Alt to release",
  "Pas de la grille": "Grid step",
  "Sélectionner": "Select",
  "Rectangle": "Rectangle",
  "Polygone — clic pour chaque sommet, Entrée pour fermer": "Polygon — click for each corner, Enter to close",
  "Contour de hall — un clic par angle, segments redressés, Entrée pour fermer": "Hall outline — one click per corner, straightened sides, Enter to close",
  "Ligne — clic pour chaque point, Entrée pour terminer": "Line — click for each point, Enter to finish",
  "Texte": "Text",
  "Image": "Image",
  "Repère — WC, entrée, accueil…": "Landmark — toilets, entrance, reception…",
  "Stand — matérialiser un exposant ou un co-exposant sur son emplacement": "Stand — draw an exhibitor or co-exhibitor on its space",
  "Arrondi": "Corner radius",
  "Redresser les segments": "Straighten sides",
  "Épaisseur": "Thickness",
  "Fin": "Thin",
  "Normal": "Normal",
  "Épais": "Thick",
  "Très épais": "Very thick",
  "Style": "Style",
  "Continu": "Solid",
  "Pointillé": "Dashed",
  "Flèche": "Arrow",
  "Aucune": "None",
  "Au bout": "At the end",
  "Au départ": "At the start",
  "Aux deux bouts": "At both ends",
  "Texte à placer": "Text to place",
  "Ce que le repère est": "What the landmark is",
  "Libellé — « Nord », « A »…": "Label — “North”, “A”…",
  "Exposant à matérialiser": "Exhibitor to draw",
  "Choisir une image…": "Choose an image…",
  "Supprimer — Suppr": "Delete — Del",
  "Passages vers d'autres plans": "Links to other maps",
  "Largeur": "Width",
  "Hauteur": "Height",
  "Taille": "Size",
  "Lier à un stand — numéro ou exposant": "Link to a stand — number or exhibitor",
  "Exposant — numéro ou nom": "Exhibitor — number or name",
  "Annuler · Ctrl+Z": "Undo · Ctrl+Z",
  "Terminer — Échap": "Done — Esc",
  "Terminer le placement des libellés": "Finish placing labels",
  "Placement automatique": "Automatic placement",
  "Fermer": "Close",
  "Ordre des calques": "Layer order",

  "Nouvel exposant": "New exhibitor",
  "Modifier la fiche": "Edit details",
  "Détail": "Details",
  "Programme": "Programme",

  "Mon parcours": "My visit",
  "Parcours de visite": "Visit plan",
  "Organiser ma journée": "Plan my day",
  "Partager mon parcours": "Share my visit plan",
  "Partager": "Share",
  "Vider le parcours": "Clear my visit plan",
  "Changer l'heure d'arrivée": "Change arrival time",
  "Revenir à ma liste": "Back to my list",

  "Itinéraire": "Directions",
  "Se rendre": "Getting there",
  "à définir": "to be set",
  "Départ": "Start",
  "Arrivée": "Destination",
  "Entrée, stand, zone…": "Entrance, stand, area…",
  "Choisir le départ sur le plan": "Pick the start on the map",
  "Inverser le départ et l'arrivée": "Swap start and destination",
  "Nom ou numéro de stand": "Stand name or number",
  "Choisir l'arrivée sur le plan": "Pick the destination on the map",
  "Itinéraire accessible": "Accessible route",
  "Évite les escaliers et les escalators, les obstacles signalés, et les passages de moins d'un mètre quarante.":
    "Avoids stairs and escalators, reported obstacles, and passages narrower than 1.40 metres.",
  "Effacer l'itinéraire": "Clear route",
};
