/* `outils/gabarit/_js.html` — l'index, la recherche et ses critères, la liste,
   la fiche d'un stand, d'une zone ou d'une conférence. */
module.exports = {
  "Administration — {salon}": "Admin — {salon}",
  "{n} pavillons": "{n} halls",
  "{n} pavillon": "{n} hall",
  "Stand": "Stand",
  "Stand {code}": "Stand {code}",
  "Zone": "Area",
  "zone": "area",
  "Conf": "Talk",
  "Repère": "Landmark",

  // les critères
  "Secteur": "Sector",
  "Ville": "City",
  "Pays": "Country",
  "Nomenclature": "Categories",
  "Thématiques": "Themes",
  "Retirer ce critère": "Remove this filter",
  "Retirer le critère {critere} {valeur}": "Remove filter {critere} {valeur}",
  "Tout effacer": "Clear all",
  "{n} exposants retenus": "{n} exhibitors match",
  "{n} exposant retenu": "{n} exhibitor matches",
  "0 exposant retenu": "0 exhibitors match",
  "aucune valeur relevée": "no values found",
  "retenu": "selected",
  "{n} retenue": "{n} selected",
  "{n} retenues": "{n} selected",
  "Aucune valeur sur les fiches. Vérifiez le champ d'origine de ce champ dans la console, puis lancez une synchronisation : les valeurs proposées ici viennent d'elle.":
    "No values on the exhibitor records. Check where this field comes from in the console, then run a synchronisation: the values offered here come from it.",
  "Aucune valeur ne correspond.": "No value matches.",
  "Filtrer {critere}…": "Filter {critere}…",
  "Voir les résultats": "Show results",

  // la liste
  "{n} résultats": "{n} results",
  "{n} résultat": "{n} result",
  "tous pavillons": "all halls",
  "Zone sans nom": "Unnamed area",
  "Aucun résultat dans les {n} pavillons.": "No results in the {n} halls.",
  "Aucun résultat dans les 1 pavillons.": "No results in the hall.",
  "0 résultat": "0 results",

  // la fiche
  "Raison sociale": "Company name",
  "Adresse": "Address",
  "Niveaux": "Levels",
  "Téléphone": "Phone",
  "Site web": "Website",
  "Facebook": "Facebook",
  "LinkedIn": "LinkedIn",
  "Instagram": "Instagram",
  "Description": "Description",
  "Lien": "Link",
  "Conférences": "Conferences",
  "Centrer sur le plan": "Centre on map",
  "Sans nom": "Unnamed",
  "{n} sociétés occupent ce stand.": "{n} companies share this stand.",
  "{n} exposants ici": "{n} exhibitors here",
  "Affiché : oui": "Shown: yes",
  "Affiché : non": "Shown: no",
  "Retirer cette zone du plan public": "Remove this area from the public map",
  "Remettre cette zone sur le plan public": "Put this area back on the public map",

  // la fiche d'une conférence
  "Quand": "When",
  "Où": "Where",
  "Organisée par": "Hosted by",
  "Intervenants": "Speakers",
  "Animée par": "Moderated by",
  "Thématique": "Theme",
  "Présentation": "Presentation",
  "Situer sur le plan": "Show on map",
};
