/* `outils/gabarit/_rapport-js.html` — le rapport d'utilisation d'un salon. */
module.exports = {
  "{n} derniers jours": "Last {n} days",
  "Depuis le début": "Since the start",
  "Programme d'une salle": "A room's programme",
  "Fiche d'un exposant": "An exhibitor's details",
  "Navigateur": "Browser",
  "Le plan ouvert dans un onglet.": "The map opened in a browser tab.",
  "Cadre sur un site": "Frame on a website",
  "Encadré dans la page d'un site ou d'une application tierce.": "Embedded in a page of a third-party website or app.",
  "Écran d'accueil": "Home screen",
  "Installé sur l'appareil, lancé hors du navigateur.": "Installed on the device, launched outside the browser.",
  "Application": "App",
  "Servi par une coque déposée sur une boutique.": "Served by a wrapper app published on a store.",
  "Non précisé": "Not specified",
  "Compté avant que la porte d'accès ne le soit.": "Counted before the way in was recorded.",
  "visites": "visits",
  "dont {n} au stockage refusé": "including {n} with storage blocked",
  "{n} fiches ouvertes": "{n} records opened",
  "{n} fiche ouverte": "{n} record opened",
  "Connectez-vous pour lire le rapport.": "Sign in to read the report.",
  "Aucun événement.": "No events.",
  "Créez-en un depuis la console.": "Create one from the console.",
  "Voir le plan": "View the map",
  "Aucune mesure pour cet événement.": "No measurements for this event.",
  "Les visites sont comptées dès la première ouverture du plan public.": "Visits are counted from the first time the public map is opened.",
  "L'événement est en brouillon : son plan n'est pas encore servi aux visiteurs.": "The event is a draft: its map is not yet served to visitors.",
  "Fréquentation": "Attendance",
  "Visites": "Visits",
  "Une ouverture du plan. Revenir plus tard en fait une seconde.": "One opening of the map. Coming back later makes a second one.",
  "Navigateurs distincts sur la période.": "Distinct browsers over the period.",
  "Dont {n} au stockage refusé, recomptés à chaque ouverture.": "Including {n} with storage blocked, counted again at each opening.",
  "Navigateurs distincts sur la période. Dont {n} au stockage refusé, recomptés à chaque ouverture.":
    "Distinct browsers over the period. Including {n} with storage blocked, counted again at each opening.",
  "Recherches": "Searches",
  "Mots-clés saisis, doublons écartés.": "Keywords typed, duplicates removed.",
  "Trajets distincts demandés.": "Distinct routes requested.",
  "Programmes de visite": "Visit plans",
  "{n} ajouts ou retraits au total.": "{n} additions or removals in total.",
  "{n} ajout ou retrait au total.": "{n} addition or removal in total.",
  "Parcours partagés": "Shared visit plans",
  "{n} étapes reprises par ceux qui les ont reçus.": "{n} stops taken up by those who received them.",
  "{n} étape reprise par ceux qui les ont reçus.": "{n} stop taken up by those who received them.",
  "Aucune étape reprise pour l'instant.": "No stops taken up yet.",
  "Par moyen d'accès": "By way in",
  "Les visites ne se comparent pas d'une porte à l'autre : rouvrir une application en ouvre une à chaque fois, un cadre en ouvre une par page du site qui le porte. Et la somme des visiteurs dépasse le total ci-dessus — un navigateur, une application et un cadre posé sur un site tiers ne partagent aucun jeton, le même visiteur y compte une fois par porte et une seule au total.":
    "Visits cannot be compared from one way in to another: reopening an app starts a new one each time, and a frame starts one per page of the site that hosts it. And the sum of visitors exceeds the total above — a browser, an app and a frame on a third-party site share no token, so the same visitor counts once per way in and only once in the total.",
  "Tout est passé par la même porte sur cette période.": "Everything came through the same way in over this period.",
  "La porte d'accès n'était pas encore comptée sur cette période.": "The way in was not yet recorded over this period.",
  "Fiches exposants ouvertes": "Exhibitor records opened",
  "Toutes provenances confondues.": "All sources combined.",
  "Par canal": "By channel",
  "Fiches conférences ouvertes": "Conference records opened",
  "Une conférence s'ouvre depuis le programme de la salle qui l'accueille, depuis la fiche de l'exposant qui la tient, ou depuis le programme de visite. Elle n'a ni recherche ni forme propre sur le plan.":
    "A conference is opened from the programme of the room hosting it, from the record of the exhibitor running it, or from the visit plan. It has no search and no shape of its own on the map.",
  "Jour par jour": "Day by day",
  "Visites par jour, dans le fuseau du salon ({fuseau}).": "Visits per day, in the show's time zone ({fuseau}).",
  "Mesure ouverte depuis le {date}.": "Measured since {date}.",
  "Visites par jour, dans le fuseau du salon ({fuseau}). Mesure ouverte depuis le {date}.":
    "Visits per day, in the show's time zone ({fuseau}). Measured since {date}.",
};
