/* Ce qui arrive par les données et non par le code : des valeurs que toutes
   les fiches partagent, quel que soit le salon.

   Une clé ne vaut que pour une chaîne entière — « Belgique » seule dans sa
   case, jamais « Belgique » au milieu d'une adresse. On n'y met donc que ce qui
   se lit seul et ne peut guère être autre chose : une enseigne ne s'appelle pas
   « Pays-Bas ». Un prénom qui est aussi un pays (« Maurice ») n'y a pas sa
   place. Toute page qui interroge le serveur emporte ce fichier. */
module.exports = {
  "Oui": "Yes",
  "Non": "No",
  "oui": "yes",
  "non": "no",

  // les titres de groupe qu'on retrouve d'un salon à l'autre sur les fiches
  "Réseaux sociaux": "Social media",
  "Coordonnées": "Contact details",
  "Contact": "Contact",
  "Contacts": "Contacts",
  "Localisation": "Location",
  "Activité": "Business",
  "Activités": "Activities",
  "Secteur d'activité": "Business sector",
  "Département": "Department",
  "Région": "Region",
  "Pavillon {n}": "Hall {n}",
  "Hall {n}": "Hall {n}",

  // les pays, tels que les fiches d'exposants les portent
  "Afrique du Sud": "South Africa",
  "Algérie": "Algeria",
  "Allemagne": "Germany",
  "Andorre": "Andorra",
  "Arabie saoudite": "Saudi Arabia",
  "Argentine": "Argentina",
  "Australie": "Australia",
  "Autriche": "Austria",
  "Belgique": "Belgium",
  "Brésil": "Brazil",
  "Bulgarie": "Bulgaria",
  "Cameroun": "Cameroon",
  "Chine": "China",
  "Chypre": "Cyprus",
  "Colombie": "Colombia",
  "Corée du Sud": "South Korea",
  "Croatie": "Croatia",
  "Côte d'Ivoire": "Ivory Coast",
  "Danemark": "Denmark",
  "Égypte": "Egypt",
  "Émirats arabes unis": "United Arab Emirates",
  "Espagne": "Spain",
  "Estonie": "Estonia",
  "États-Unis": "United States",
  "Finlande": "Finland",
  "Grèce": "Greece",
  "Guyane": "French Guiana",
  "Hongrie": "Hungary",
  "Île Maurice": "Mauritius",
  "Inde": "India",
  "Irlande": "Ireland",
  "Islande": "Iceland",
  "Israël": "Israel",
  "Italie": "Italy",
  "Japon": "Japan",
  "La Réunion": "Réunion",
  "Lettonie": "Latvia",
  "Liban": "Lebanon",
  "Lituanie": "Lithuania",
  "Malte": "Malta",
  "Maroc": "Morocco",
  "Mexique": "Mexico",
  "Norvège": "Norway",
  "Nouvelle-Calédonie": "New Caledonia",
  "Nouvelle-Zélande": "New Zealand",
  "Pays-Bas": "Netherlands",
  "Pérou": "Peru",
  "Pologne": "Poland",
  "Polynésie française": "French Polynesia",
  "République tchèque": "Czech Republic",
  "Roumanie": "Romania",
  "Royaume-Uni": "United Kingdom",
  "Russie": "Russia",
  "Sénégal": "Senegal",
  "Singapour": "Singapore",
  "Slovaquie": "Slovakia",
  "Slovénie": "Slovenia",
  "Suède": "Sweden",
  "Suisse": "Switzerland",
  "Tunisie": "Tunisia",
  "Turquie": "Turkey",
};
