/* `outils/gabarit/modules/polices-plan.mjs` — les polices au choix pour les noms
   du plan, et leurs genres. */
module.exports = {
  // les genres, qui filtrent les vignettes
  "Sans serif": "Sans serif",
  "Étroites": "Condensed",
  "Serif": "Serif",
  "Arrondies": "Rounded",
  "Haute lisibilité": "High legibility",
  "Affiche": "Display",
  "Manuscrites": "Handwritten",
  "Chasse fixe": "Monospace",
  // les noms des polices, identiques dans les deux langues
  "Archivo": "Archivo",
  "Barlow": "Barlow",
  "DM Sans": "DM Sans",
  "Fira Sans": "Fira Sans",
  "IBM Plex Sans": "IBM Plex Sans",
  "Instrument Sans": "Instrument Sans",
  "Inter": "Inter",
  "Jost": "Jost",
  "Lato": "Lato",
  "Manrope": "Manrope",
  "Montserrat": "Montserrat",
  "Noto Sans": "Noto Sans",
  "Open Sans": "Open Sans",
  "Plus Jakarta Sans": "Plus Jakarta Sans",
  "Poppins": "Poppins",
  "Raleway": "Raleway",
  "Roboto": "Roboto",
  "Source Sans 3": "Source Sans 3",
  "Space Grotesk": "Space Grotesk",
  "Work Sans": "Work Sans",
  "Anton": "Anton",
  "Archivo Narrow": "Archivo Narrow",
  "Barlow Condensed": "Barlow Condensed",
  "Bebas Neue": "Bebas Neue",
  "Fira Sans Condensed": "Fira Sans Condensed",
  "Oswald": "Oswald",
  "PT Sans Narrow": "PT Sans Narrow",
  "Roboto Condensed": "Roboto Condensed",
  "Bitter": "Bitter",
  "Cormorant Garamond": "Cormorant Garamond",
  "EB Garamond": "EB Garamond",
  "Fraunces": "Fraunces",
  "Libre Baskerville": "Libre Baskerville",
  "Lora": "Lora",
  "Merriweather": "Merriweather",
  "Playfair Display": "Playfair Display",
  "PT Serif": "PT Serif",
  "Roboto Slab": "Roboto Slab",
  "Source Serif 4": "Source Serif 4",
  "Comfortaa": "Comfortaa",
  "Fredoka": "Fredoka",
  "Nunito": "Nunito",
  "Quicksand": "Quicksand",
  "Varela Round": "Varela Round",
  "Andika": "Andika",
  "Atkinson Hyperlegible Next": "Atkinson Hyperlegible Next",
  "Lexend": "Lexend",
  "Abril Fatface": "Abril Fatface",
  "Alfa Slab One": "Alfa Slab One",
  "Archivo Black": "Archivo Black",
  "Bungee": "Bungee",
  "Righteous": "Righteous",
  "Caveat": "Caveat",
  "Dancing Script": "Dancing Script",
  "Kalam": "Kalam",
  "Patrick Hand": "Patrick Hand",
  "Courier Prime": "Courier Prime",
  "IBM Plex Mono": "IBM Plex Mono",
  "Inconsolata": "Inconsolata",
  "JetBrains Mono": "JetBrains Mono",
  "Roboto Mono": "Roboto Mono",
  "Space Mono": "Space Mono",
};
